baseURL: https://satwikvats.github.io
languageCode: en-us
title: "Know me better.."
theme: "toha"

# Use Hugo modules to add theme
#module:
  #imports:
  #- path: github.com/hugo-toha/toha/v4
  #- path: https://github.com/hugo-toha/toha/v4


# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  #background: /images/site/background.jpg

  #logo:
    #main: /images/site/main-logo.png
    #inverted: /images/site/inverted-logo.png
    #favicon: /images/site/favicon.png
  
  # GitHub repo URL and branch of your site
  #gitRepo: https://github.com/hugo-toha/hugo-toha.github.io
  gitRepo: https://github.com/SatwikVats/SatwikVats.github.io
  gitBranch: main

  topNavbar:
    maxVisibleSections: 5

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  features:

    # Enable dark theme
    darkMode:
      enable: true
      services:
        darkreader:
          defaultColorScheme: dark # options are 'system', 'dark', 'light'
          fixes:
            invert: ['img[src$=".svg"]'] # inverts svg colors.
          theme:
            brightness: 100
            contrast: 100
            sepia: 0

    # Enable and configure portfolio
    portfolio:
      enable: true

    # Enable and configure blog posts
    blog:
      enable: true
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true
        email: true
        # tumblr: true
        # pocket: true
        # diaspora: true
        # mastodon: true


  #Dark theme
  darkMode:
    enable: true
    provider: darkreader
    default: dark
  
  # specify whether you want to write some blog posts or not
  #enableBlogPost: true

  

  # specify whether you want to show Table of Contents in reading page
    toc:
      enable: true

    # Show tags under the post title
    tags:
      enable: true

    # Specify whether to show flag in the language selector. Default is true.
    flags:
      enable: true
      # # If you want to use different country flag for a language, specify them here.
      # flagOverwrites:
      #   - languageCode: en
      #     countryCode: us

    # Enable this to use `embed-pdf` shortcode.
    embedpdf:
      enable: true

    # Enable this to create flowcharts using shortcodes.
    flowchart:
      enable: false
      services:
        # Uncomment for `mermaid` shortcode.
        mermaid:
          # For config options, see: https://mermaid-js.github.io/mermaid/#/Setup?id=configuration
          theme: dark

    # Enable this to create mathematic expressions using `$$` blocks
    math:
      enable: false
      services:
        # https://katex.org/docs/autorender.html#api for more configurations
        katex:
          delimiters:
            - left: $$
              right: $$
              display: true
            - left: \\[
              right: \\]
              display: true
            - left: $
              right: $
              display: false
            - left: \\(
              right: \\)
              display: false

    syntaxHighlight:
      enable: true
      services:
        hljs:
          # see: https://highlightjs.readthedocs.io/en/latest/api.html#configure
          noHighlightRe: /^no-highlight$/i

    # Enable to use `video-player` shortcode
    videoPlayer:
      enable: true
      services:
        # convert .js-player class into video player via https://plyr.io/
        # Can play HTML5 Video, Audio, Youtube, Vimeo.
        # For more info on setup: https://github.com/sampotts/plyr#quick-setup
        plyr:
          # options doc: https://github.com/sampotts/plyr#options
          # fullscreen: true

  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
      # show custom menus in the footer
      customMenus: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true


  # Provide newsletter configuration. 
  # This feature has been implemented for Mailchimp only for now.
  # You can also hide it from the footer.
  newsletter:
    # specify whether you want to display the newsletter form 
    enable: false
    # specify which newsletter provider you want to use
    provider: mailchimp
    # specify the target URL for the subscription form
    mailchimpURL: https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e
