# Update dependencies

version: 3.6.0
updates:
# Update the Github Action  versions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
  - "dependencies"
  - "automerge"
  - "enhancement"
